http:
  client-type: REST_TEMPLATE
  http-client:
    enable-delay-before-quote-info-request: true
    delay-time-before-quote-info-request-ms: 50
  rest-template:
    max-total-connection-count: 50
    connection-request-timeout: 50000
stock-quotes:
  thread-count: 5
  scheduler-thread-count: 1
  count-top-volume-companies: 5
  count-top-volatile-companies: 5
  scheduler:
    company-update-period-ms: 50
    log-result-period-ms: 5000
  iex:
    base-url: https://sandbox.iexapis.com
    symbols-path: /stable/ref-data/symbols
    quote-info-path: /stable/stock/{stock code}/quote
    token: ${iex.token}
spring:
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50

logging:
  level:
    me:
      bezgerts: INFO
